// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate env vars without crashing the whole app
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[Supabase] Missing environment variables. Check your .env file:\n' +
    '  VITE_SUPABASE_URL=' + (SUPABASE_URL ? '✓' : '✗ MISSING') + '\n' +
    '  VITE_SUPABASE_PUBLISHABLE_KEY=' + (SUPABASE_PUBLISHABLE_KEY ? '✓' : '✗ MISSING')
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Detect session in URL (OAuth redirect, magic link)
      detectSessionInUrl: true,
      // Flow type for PKCE (more secure for SPAs)
      flowType: 'pkce',
    },
    // Global fetch timeout
    global: {
      fetch: (url, options = {}) => {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 30_000); // 30s timeout
        return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timeout));
      },
    },
    // Realtime config
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);
